@startuml dyndns_dhcp
title "Dynamic DNS with DHCP"

scale 200
skinparam SequenceMessageAlignment center

participant "Client 'CL01'" as CL order 1
participant "DNS Server" as DNS order 3
participant "DHCP Server" as DHCP order 2

CL -> DHCP: What IP?
note left
This is simplified
end note

DHCP -> CL: Your IP = **10.100.15.1**
DHCP -> DNS: **CL01** => **10.100.15.1**
@enduml
